### ISSUE TITLE
console.log not available on IE

### ISSUE THREAD

**Issue by francisdb** [JakeWharton/jquery-maven-artifact#1]
As console.log is not available on internet explorer\* you should probably check if it exists before calling it.
- It's only available after opening the dev console: http://theablefew.com/blog/internet-explorer-and-console-log

**Comment by JakeWharton** [comment]
That is amazingly awful. Thanks for the tip, will update.

**Comment by JakeWharton** [comment]
Fixed by f28c6ce.
